---
- hosts: voldenuit
  remote_user: pi
  vars:
    zhaoxiangjs_dir: /home/pi/sources/zhaoxiangjs
    zhaoxiangjs_repo: git@github.com:soixantecircuits/zhaoxiangjs.git
    watchy_dir: /home/pi/sources/watchy
    watchy_repo: git@github.com:soixantecircuits/watchy.git
    node_dir: /usr/local/bin
  tasks:
    - name: "cronjob to clean old snaps hourly"
      cron: name="clean old snaps" minute="12" job="/usr/bin/find /tmp/snaps -mmin +59 -and -not -type d -delete"
    - name: "cronjob to clean old stream hourly (mjpg_streamer should delete them already)"
      cron: name="clean old snaps" minute="42" job="/usr/bin/find /tmp/stream -mmin +59 -and -not -type d -delete"
