---
- hosts: testvol
  remote_user: pi
  vars:
    zhaoxiangjs_dir: /home/pi/sources/zhaoxiangjs
    zhaoxiangjs_repo: git@github.com:soixantecircuits/zhaoxiangjs.git
    watchy_dir: /home/pi/sources/watchy
    watchy_repo: git@github.com:soixantecircuits/watchy.git
    node_dir: /usr/local/bin
  tasks:
    - cron: name="slack message at restart" special_time=reboot job="sleep 30;HOSTNAME=$(cat /etc/hostname);curl -X POST --data-urlencode 'payload={\"channel\":\"#avengers\", \"username\":\"voldenuit\", \"text\":\"'$HOSTNAME' just restarted\", \"icon_emoji\":\":ghost:\"}' https://hooks.slack.com/services/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"
