---
- hosts: testvol
  remote_user: pi
  vars:
    zhaoxiangjs_dir: /home/pi/sources/zhaoxiangjs
    zhaoxiangjs_repo: git@github.com:soixantecircuits/zhaoxiangjs.git
    watchy_dir: /home/pi/sources/watchy
    watchy_repo: git@github.com:soixantecircuits/watchy.git
    node_dir: /usr/local/bin
  tasks:
    - name: setup watchy in pm2  
      shell: pm2 start {{watchy_dir}}/app.js --name "watchy" --log-date-format "YYYY-MM-DD HH:mm Z"
      ignore_errors: yes
    - name: setup zhaoxiangjs in pm2  
      shell: pm2 start {{zhaoxiangjs_dir}}/app.js --name "zhaoxiangjs" --log-date-format "YYYY-MM-DD HH:mm Z"
      ignore_errors: yes
    - name: save pm2 status
      shell: pm2 save
